### PR TITLE
Finish mobile version

### PR DESCRIPTION
**Pull request by adel-gu**
### Requirements Completed in this Project

1. Add and style the Project section.
2. Add and style the About section.

### CODE REVIEW

**Review by frank1738 — CHANGES_REQUESTED** [review]
Hi @adel-gu , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

almost there

## Highlights
- Passing Linters

## Required Changes ♻️
- [REQUIRED ] Your project is incomplete.
   - On your project section, you only have one project. would you please add five more projects to meet the Figma requirements
   
image
- Would you please add the `about me` section

image



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by adel-gu** [comment]
Hi @frank1738,
I did add the sections missing from the project,
I appreciate your efforts and thank you so much.

**Review by adel-gu — COMMENTED** [review]
Hi @frank1738 
Thank you so much for your efforts, I actually did accomplish those tasks you included in your review.
Appreciate that a lot, once again thank you.

**Review by emmiiorji — APPROVED** [review]
Hi @adel-gu, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

congrats


## Good Highlights ✅
- Meaningful commit messages
- Linter checks are passing
- Requested changes have been implemented
- Design is beautiful

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
